### ISSUE TITLE
[ISSUE] Unhandled Exception: This widget has been unmounted, so the State no longer has a context (and should be considered defunct).

### ISSUE THREAD

**Issue by PTLam25** [chooyan-eng/crop_your_image#57]
When closing page with CropEditor there is error in the console.

It happens in the method _resetCroppingArea  when getting screenSize from context:
```dart
void _resetCroppingArea() {
    final screenSize = MediaQuery.of(context).size;

    final imageRatio = _targetImage!.width / _targetImage!.height;
    _isFitVertically = imageRatio < screenSize.aspectRatio;

    _imageRect = calculator.imageRect(screenSize, imageRatio);

    _resizeWith(widget.aspectRatio, widget.initialArea);
  }
```
![image](https://user-images.githubusercontent.com/83693224/145966208-758d8f38-e7eb-4ffe-82bd-501581008e87.png)

**Comment by ShineYang** [comment]
Same issue.

**Comment by chooyan-eng** [comment]
@PTLam25 @ShineYang 
Hi, thank you for the issue.

I guess `_CropEditor` needs proper `dispose()` method.

Wait for update or I'll appreciate your pull requests if you have an idea to solve this.

**Comment by ChristophKe** [comment]
Same Problem here...

**Comment by nyqvistatwork** [comment]
Still a problem

**Comment by NikoBoerger** [comment]
I'm having the same issue in my WidgetTests, where this Widget is shown on one of my app pages:

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞══
The following assertion was thrown running a test (but after the test had completed):
This widget has been unmounted, so the State no longer has a context (and should be considered
defunct).
Consider canceling any active work during "dispose" or using the "mounted" getter to determine if
the State is still active.

When the exception was thrown, this was the stack:
#0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:951:9)
#1      State.context (package:flutter/src/widgets/framework.dart:957:6)
#2      _CropEditorState._resetCroppingArea (package:crop_your_image/src/crop.dart:369:38)
#3      _CropEditorState.didChangeDependencies.<anonymous closure> (package:crop_your_image/src/crop.dart:339:9 

Would appreciate an update. Thanks so much :)
