### ISSUE TITLE
Aborting the crop during load leads to an error

### ISSUE THREAD

**Issue by tp** [chooyan-eng/crop_your_image#76]
The cropper does a bit of async work on start up, and if the user / app dismisses the widget during that time, errors will be thrown due to `context` being accessed after it has been unmounted.

This happens e.g. in https://github.com/chooyan-eng/crop_your_image/blob/c80794432d2fb5f45d541248c2b6df6adb6078d4/lib/src/crop.dart#L369

I think all the `future.then` need to the `mounted` in the callback before doing anything else.

```
E/flutter (14746): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
E/flutter (14746): Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
E/flutter (14746): #0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:935:9)
E/flutter (14746): #1      State.context (package:flutter/src/widgets/framework.dart:941:6)
E/flutter (14746): #2      _CropEditorState._resetCroppingArea (package:crop_your_image/src/crop.dart:369:38)
E/flutter (14746): #3      _CropEditorState.didChangeDependencies.<anonymous closure> (package:crop_your_image/src/crop.dart:339:9)
E/flutter (14746): <asynchronous suspension>
E/flutter (14746): 
```

And from Firebase:

<img width="774" alt="CleanShot 2022-11-17 at 15 24 39@2x" src="https://user-images.githubusercontent.com/52437/202471866-bdc9bee1-0457-4a80-a1bc-2c93a2619b40.png">

**Comment by chooyan-eng** [comment]
@tp 
Thank you for your feedback.
I'll check the problem and fix this.
